### ISSUE TITLE
the question about  Image Content-Extractor

### ISSUE THREAD

**Issue by HDUyiming** [XiaRho/CMDA#3]
您的文章给我带了很大的启发，但是我有几处不太明白的地方还请您多多赐教！
1.您是使用灰度图像进行F_Filter操作的，那么在获取到I_CE后是否还要转为三通道图像呢？
2.进行F_Filter操作的图像是否在数据载入阶段已经进行了数值归一化操作？如果没有做的话，那么F_Filter操作后还需要进行吗？
3.模型能够适应这种经过F_Filter操作后的图像吗？（因为我觉得这种操作之后图像的分布会发生很大偏移，我想将此操作用于目标检测的暗夜检测上，不知道是否可行）
再次感谢！

**Comment by XiaRho** [comment]
1. yes, all converted to three channels and then fed into the network
2. the input image for F_Filter is already normalised
3. the model's Events Encoder is used to process the image obtained by the F_Filter, while the RGB image is processed by the Image Encoder, so it can adapt to different distributions. I don't have much contact with night object detection, you can try to look at it

**Comment by HDUyiming** [comment]
感谢您的及时回复！我在论文的“Network Architecture.”章节中看到了您的描述，请问这两种Encoder在结构上是相似的吗？两个编码器公用一个解码器来进行预测，能否理解为解码器能够适应不同编码器对不同分布数据提取的特征？
此外您能否将公式（1）-（4）在代码中的具体位置告诉我吗？我对于您的代码结构不是特别熟悉~

**Comment by XiaRho** [comment]
1. the two encoder structures are the same. Yes, it can be understood like this
2. get_image_change_from_pil and get_ic functions in mmseg/datasets/utils.py

**Comment by HDUyiming** [comment]
好嘞~感谢指导！
