### ISSUE TITLE
How to generate the leftImg8bit_IC1 motion images?

### ISSUE THREAD

**Issue by helq2612** [XiaRho/CMDA#4]
Thank you for sharing this great work! 
Could you share the code about generate those leftImg8bit_IC1 images? I think these images are (offline) generated based on Eq 1~4, right?

**Comment by XiaRho** [comment]
Yes, the leftImg8bit_IC1 motion images are generated offline. You can refer to the get_ic function in CMDA/mmseg/datasets/utils.py and replace image_front and image_now with two neighboring frames
